language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t idankish/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true idankish/react-test npm test

after_success:
  - docker build -t idankish/multi-client ./client
  - docker build -t idankish/multi-nginx ./nginx
  - docker build -t idankish/multi-server ./server
  - docker build -t idankish/multi-worker ./worker
  - docker login -u idankish78 -p Kushksuhon41!
  - docker tag idankish/multi-client idankish78/multi-client
  - docker tag idankish/multi-nginx idankish78/multi-nginx
  - docker tag idankish/multi-server idankish78/multi-server
  - docker tag idankish/multi-worker idankish78/multi-worker
  - docker push idankish78/multi-client
  - docker push idankish78/multi-nginx 
  - docker push idankish78/multi-server 
  - docker push idankish78/multi-worker